export const CONTACTS_FETCH_SUCCESS = 'CONTACTS_FETCH_SUCCESS';

export const SWITCH_LANGUAGE = 'SWITCH_LANGUAGE';

export const SWITCH_THEME = 'SWITCH_THEME';

export const SEND_MESSAGE = 'SEND_MESSAGE';

export const MESSAGES_FETCH_SUCCESS = 'MESSAGES_FETCH_SUCCESS';

export const SET_ACTIVE_USER = 'SET_ACTIVE_USER';
