const CONTACTS_FETCH_SUCCESS = 'CONTACTS_FETCH_SUCCESS';

const SWITCH_LANGUAGE = 'SWITCH_LANGUAGE';

const SWITCH_THEME = 'SWITCH_THEME';

const SEND_MESSAGE = 'SEND_MESSAGE';

const MESSAGES_FETCH_SUCCESS = 'MESSAGES_FETCH_SUCCESS';

const SET_ACTIVE_USER = 'SET_ACTIVE_USER';

const GET_MESSAGE = 'GET_MESSAGE';

export default {
  CONTACTS_FETCH_SUCCESS,
  SWITCH_LANGUAGE,
  SWITCH_THEME,
  MESSAGES_FETCH_SUCCESS,
  SET_ACTIVE_USER,
  GET_MESSAGE,
  SEND_MESSAGE
}
